---
AWSTemplateFormatVersion: 2010-09-09
Description: gp2-3 director lambda execution role

Resources:
  DirectorLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - sts:AssumeRole
      Path: /
      RoleName: sreGP23DirectorLambdaRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        -
          PolicyName: sreGP23DirectorLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Sid: allowLambdaInvoke
                Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"
                Resource:
                  - !Sub "arn:aws:lambda:*:${AWS::AccountId}:function:*"
              -
                Sid: allowDescribeRegions
                Effect: "Allow"
                Action:
                  - "ec2:DescribeRegions"
                Resource:
                  - "*"
              -
                Sid: allowOrgAccounts
                Effect: "Allow"
                Action:
                  - "organizations:ListAccounts"
                Resource:
                  - "*"
              -
                Sid: allowParamStore
                Effect: "Allow"
                Action:
                  - "ssm:GetParameter"
                Resource:
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/sre/wavefront/directingest"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/dev_test/host"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/dev_test/username"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/dev_test/template_id"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/dev_test/password"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/prod/host"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/prod/username"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/prod/template_id"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/prod/password"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/preprod/host"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/preprod/username"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/preprod/template_id"
                  - !Sub "arn:aws:ssm:eu-west-1:${AWS::AccountId}:parameter/service_now/preprod/password"

